version: "3.7"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: perceptdrive
      MYSQL_PASSWORD: perceptdrive
    ports:
      - "3306:3306"
    volumes:
      - "./dbscripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./dbscripts/data.sql:/docker-entrypoint-initdb.d/2.sql"