runtime: java11
entrypoint: java -jar build/libs/perceptdrive.jar
instance_class: F2
runtime_config:
  jdk: openjdk11
automatic_scaling:
  max_idle_instances: 1
  max_instances: 3
inbound_services:
  - warmup
handlers:
  - url: /api/v1/*
    script: auto